### ISSUE TITLE
Error uploading tree to iTOL

### ISSUE THREAD

**Issue by brettChapman** [albertyw/itolapi#21]
Hi

I'm trying to use the iTOL API to access iTOL through Python and it seems that the code isn't up to date with the new iTOL version 3, as I've been getting this error message:

There was an error:ITOL VERSION 2 BATCH IS NO LONGER AVAILABLE. PLEASE USE THE CURRENT VERSION.

The iTOL API is still linked to from the iTOL web site. Are there any plans to update the python iTOL API so that it can work with the latest version of iTOL?

Thanks.

Brett

**Comment by albertyw** [comment]
I also got an email for 

```
Dear Albert,

 

I’m contacting you in relation to an error I recently got while trying to upload some trees and metadata to itol using the itolapi. I used itolapi about 3 months ago successfully (great api btw) but now it doesn’t work for me anymore. It’d be really appreciated if you could provide some help.

 

I get this error:

ITOL VERSION 2 BATCH IS NO LONGER AVAILABLE. PLEASE USE THE CURRENT VERSION.

 

I have tried changing the “itol2.embl.de” part of the scripts to “itol.embl.de” but now get another error:

‘ERR 0: zipFile is required'

 

Which I can see why in the http://itol.embl.de/help.cgi guide but solution goes by using a different set of scripts.

 

I’d be very thankful if you could let me know whether this error has to do with itol website, itolapi, or maybe something I’m doing wrong.  

 

Thank you in advance,

Rodrigo
```

I'll take a look at this soon.

**Comment by albertyw** [comment]
This has been fixed in https://github.com/albertyw/itolapi/releases/tag/v2.0.0.

Update with `pip install --upgrade itolapi`

**Comment by PollyTikhonova** [comment]
Dear @albertyw ,
I am facing up with a error ‘ERR 0: zipFile is required' during my python post request. Maybe you could help me to figure out, what am I doing wrong?
```zfile = '../tree_working_dir/tree_working_dir.zip'
UPLOAD_URL = "http://itol.embl.de/batch_uploader.cgi"
respond = requests.post(UPLOAD_URL, data=args, files={'zipFile':open(zfile, `'rb')})```

**Comment by albertyw** [comment]
@PollyTikhonova I think your `zfile` is missing, empty or otherwise incorrect.

**Comment by PollyTikhonova** [comment]
@albertyw thank you for your reply! But if it was missing, Python would notify me about it at the moment of opening zfile. And I tested, when the parameter 'zipFile' is sent with incorrect data, the server respond with another error. So, this error means that python did not sent the parameter in a correct way, but I have no idea what's wrong.

**Comment by albertyw** [comment]
What version of the `requests` package are you using?

**Comment by PollyTikhonova** [comment]
2.21.0

**Comment by PollyTikhonova** [comment]
Oh my God! Thank you!!! It worked!
