### ISSUE TITLE
Problem in create_zip_from_files function

### ISSUE THREAD

**Issue by lperepol** [albertyw/itolapi#28]
In some cases, the zip file is deleted before it is sent because it is created with a default value of delete=True. The user gets a PermissionError:

**Comment by albertyw** [comment]
Looking at the code, I don't see an issue here and I can't reproduce the bug. Reading a deleted file should return an `IOError`, not a `PermissionError`.  I made a few refactors that should ensure there aren't any issues with this function.

Reopen this task if you have a traceback or steps for reproduction.
