### ISSUE TITLE
Failure to export very large tree files

### ISSUE THREAD

**Issue by jeffreyjeromequinn** [albertyw/itolapi#31]
Hello Albert and Ivica,

Thanks so much for handling this. I can confirm, too, that the example dataset correctly exports now. Great!

Unfortunately, with considerably larger datasets (e.g. >10,000 leaves with ~20 visible datasets, I am still getting the same error. (Indeed, with >10,000 leaves and just one visible dataset, it also produces the error.) I understand that these are especially large trees and datasets. I've attached one such example below.

Thanks so much. Best wishes,
Jeff

[LG1_iTOL.zip](https://github.com/albertyw/itolapi/files/3928300/LG1_iTOL.zip)

_Originally posted by @jeffreyjeromequinn in https://github.com/albertyw/itolapi/issues/26#issuecomment-562238782_

**Comment by albertyw** [comment]
I don't think Ivica monitors the issues in this repository.  This looks more like an issue with the itol backend and not this client.  I suggest contacting Ivica directly through https://itol.embl.de/about.cgi.
