### ISSUE TITLE
How to set my APIkey and project name?

### ISSUE THREAD

**Issue by iwangtoknow** [albertyw/itolapi#32]
Hello Wang,

I'm couldn't set my `APIkey` and the `project name`.

Will my `treefile` upload to this [batch_uploader.cgi](https://itol.embl.de/batch_uploader.cgi) address?

Thanks,

WANG

**Comment by albertyw** [comment]
I don't have an itol subscription so I don't have a way of testing this.  Reading through https://itol.embl.de/help.cgi#batch, I believe you can edit the API key and project name in the `Itol` object, i.e. 

```python
itol.params['projectName'] = project_name
itol.params['APIkey'] = api_key
```

If someone can tell Ivica Letunic to give me an itol subscription, I can add better api key support.

**Comment by rhayes777** [comment]
Yeah that works perfectly

**Comment by scwwxc** [comment]
Hi Wang,  I now can run example.py after add 
itol.params['projectName'] = project_name
itol.params['APIkey'] = api_key
to example.py

but now i get annother error:
Creating the upload params
Files:
[PosixPath('tree_of_life.tree.txt'),
 PosixPath('colors_tol.txt'),
 PosixPath('labels.txt'),
 PosixPath('ranges.txt')]
Parameters:
{'APIkey': 'tUn8aXNhyvmxObz8UdsPjw',
 'projectName': 'abc',
 'treeDescription': 'ML',
 'treeName': 'Tree of Life Example',
 'uploadID': ''}

Uploading the tree.  This may take some time depending on how large the tree is and how much load there is on the itol server
There was an error:ERR 1: Invalid project name

I'v creat abc project in my itol account in the website. And i don't know how to fix this error.
Thanks

**Comment by rhayes777** [comment]
I think the projectName has to refer to a project that already exists on iTOL. 

On the browser go to "My Trees". Click the + top right to add a workspace, then click the menu button next to the workspace name to create a project.
