### ISSUE TITLE
Missing shebang

### ISSUE THREAD

**Issue by rhayes777** [albertyw/itolapi#33]
Not sure if I'm missing something but when I try to run itol.py in the terminal it tries to interpret it as bash.

I think this could be resolved by adding a shebang:

```
#!/usr/bin/env python
```

To the very top of itol.py

**Comment by albertyw** [comment]
Not sure how I didn't catch that before.  Fixed in ab6a976.

Although the README has direct execution of `itol.py` and `itolexport.py` as examples, I expect most people would prefer writing a python script to import and use this as a library rather than a CLI.

**Comment by rhayes777** [comment]
Great thanks.

Yeah I intend to use it in a python script but it's nice to use it in terminal to see it working first.
