### ISSUE TITLE
how can i run example.py with APIkey

### ISSUE THREAD

**Issue by scwwxc** [albertyw/itolapi#35]
I'v run the example file： python example.py
but i get the error information below:
Uploading the tree.  This may take some time depending on how large the tree is and how much load there is on the itol server
There was an error:ERR 0: Please provide your iTOL API key (APIkey parameter). Anonymous batch upload is not available, please check https://itol.embl.de/infoReg.cgi

I can get my APIkey value from itol website, but i do not known how to use this key value to run example.py script correct.

Thanks!

**Comment by albertyw** [comment]
You can add an api key by setting it in `params`.  

See the example in #36 .
