### ISSUE TITLE
itol_uploader.add_file() errors 

### ISSUE THREAD

**Issue by LiZhihua1982** [albertyw/itolapi#38]
![image](https://github.com/albertyw/itolapi/assets/38903973/44609f9e-7601-4ea5-b4b3-73a66039c339)

**Comment by albertyw** [comment]
`file_path` should be a python path type instead of a string: https://docs.python.org/3/library/pathlib.html#concrete-paths

an easy way of creating path types for `add_file` is:

```python
from pathlib import Path

itol_uploader.add_file(Path('tree_of_life.tree.txt'))
```

This is clarified in edde2d6
